### ISSUE TITLE
HUD Freezes On Reaching OT, OT2, etc.

### ISSUE THREAD

**Issue by MordredXYZ** [drweissbrot/cs-hud#85] opened 2023-10-02 12:13 UTC
So I took the HUD for a spin today, and hopefully got some valuable information for you! https://www.twitch.tv/videos/1940631033

However a glaring issue is that the HUD will partially lock up when you first enter OT, and every time a new OT starts, i.e. OT1, OT2, etc, and the only fix being a forced refresh every time a new OT is reached.

Similarly, in Overtime, the round counter up the top will show 1/6, 2/6, and then not change for Round 3 but updates to Round 4 afterwards.

You should be able to find examples of both of these in my VOD linked above, in the first two matches. Match 1 has OT2, Match 2 has OT5. I hope this VOD helps with seeing things in live production!

**Comment by drweissbrot** [comment] 2023-10-03 02:52
These were CS2 matches, right?
Are there demos available for one of the OT matches by any chance?
Overtimes in CS2 matchmaking seem to work perfectly fine, I didn't find any CS2 demos on HLTV, and I couldn't get any Faceit demos to even play at all :D

If you don't have any demos, could you try to record a POV demo next time you're casting? Might still not work, would like to give it a try :D

**Comment by MordredXYZ** [comment] 2023-10-08 05:04
Sorry for the hella late reply! I investigated into if I could share demo files externally, and the answer was a no, I'm afraid.

There is a match on tonight that I'll be broadcasting, I'll happily link you the VOD once I'm done, but for now here's the hltv link: https://www.hltv.org/matches/2367227/hsg-fe-vs-stacks-of-cash-esl-impact-league-season-4-finals-asia-pacific-open-qualifier

Hopefully this will help nail down the cause(s)! Otherwise, I'm hearing plenty of positive feedback around your HUD, and I've also been plugging it every time someone mentions it, with a link in my bio on Twitch.

**Comment by drweissbrot** [comment] 2023-10-08 05:20
I don't think I can do much with a VOD unfortunately :/ But different strategy, this might work:
Open up the HUD in your browser (http://localhost:31982/hud), and press Ctrl+Shift+J. Then get to an OT where the HUD breaks (I'd assume this happens when watching a demo if you have one available, but if it doesn't, maybe you could leave this browser tab open in the background during your broadcast tonight?)
Then, when the HUD breaks (before you refresh it!), right-click in the Console panel (the one that opened when you pressed Ctrl+Shift+J), right click, Save as... (Chrome)/Save all messages to file (Firefox) -- then either upload it here or [send me an email with it](mailto:cs-hud@drweissbrot.net).
That log file should tell me where the issue is :D

**Comment by drweissbrot** [comment] 2024-01-07 23:20
Is this still an issue on [v2.3.0](https://github.com/drweissbrot/cs-hud/releases/tag/v2.3.0)?

**Comment by drweissbrot** [comment] 2024-01-22 03:48
Gonna close this one for now, feel free to reopen if you're still seeing this.

**Closed by drweissbrot** 2024-01-22 03:48 UTC
Labels: bug
