### ISSUE TITLE
Radar is lagged

### ISSUE THREAD

**Issue by juangarciatn** [drweissbrot/cs-hud#147] opened 2024-02-17 08:32 UTC
I have a question, why radar looks lagged? You can see how it is lagged on this video https://www.youtube.com/watch?v=xxlfB91jy2A&t=5839s

**Comment by drweissbrot** [comment] 2024-02-18 03:31
In the video it looks like it's not just the radar, but the entire HUD that's lagging, so I'll assume this is a duplicate of #125.

As a workaround, try limiting the game's FPS (e.g. by typing `fps_max 60` in the in-game console).

**Closed by drweissbrot** 2024-02-18 03:31 UTC
