### ISSUE TITLE
Smokes sometimes disappear too quickly

### ISSUE THREAD

**Issue by 42Firehawk** [drweissbrot/cs-hud#89] opened 2023-10-09 03:24 UTC
Used the hud in a recent match, and on a few occasions the circle for a smoke on the map would disappear well before the smoke itself started to fade away. As a note, looking into the terminal after the match reported this error it appears once per round? can't tell for certain if that's why that's reported or just close to the right total number.

  TypeError: Cannot read properties of undefined (reading 'activity')
      at updateRoundDamages (C:\snapshot\app\cs-hud.js)
      at updateAdditionalState (C:\snapshot\app\cs-hud.js)
      at C:\snapshot\app\cs-hud.js
      at dispatch (C:\snapshot\app\cs-hud.js)
      at C:\snapshot\app\cs-hud.js
      at dispatch (C:\snapshot\app\cs-hud.js)
      at C:\snapshot\app\cs-hud.js
      at dispatch2 (C:\snapshot\app\cs-hud.js)
      at dispatch (C:\snapshot\app\cs-hud.js)
      at bodyParser2 (C:\snapshot\app\cs-hud.js)

demo URL (can't upload due to size restriction)
https://cscdemos.nyc3.cdn.digitaloceanspaces.com/s12/M02/s12-M02-Cheetahs-vs-Nekomatas-mid2304-1_None-2023-10-09%2002:49:01.976060+00:00.dem.zip

**Comment by 42Firehawk** [comment] 2023-10-18 15:59
Took a glance at the code and it seems like it might be that the timer starts from grenade thrown rather than bloom? Though it's not entirely clear when the timer for it does trigger from so that could be incorrect.

**Comment by drweissbrot** [comment] 2023-11-22 11:28
I couldn't reproduce this in my recent demos, and the demo you uploaded seems to crash my game (I guess the demo format isn't as backwards compatible as it should be :D)
Have you seen this in a more recent match that you could upload the demo from? Best case with a round number/timestamp

**Comment by drweissbrot** [comment] 2024-01-07 23:20
Is this still an issue on [v2.3.0](https://github.com/drweissbrot/cs-hud/releases/tag/v2.3.0)?

**Comment by drweissbrot** [comment] 2024-01-22 03:48
Gonna close this one for now, feel free to reopen if you're still seeing this.

**Closed by drweissbrot** 2024-01-22 03:48 UTC
Labels: bug
